name: same_team_flutter
description: A new Flutter project for managing team chores and rewards.

# publish_to: 'none' # Remove this line if you plan to publish the package

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.0.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logodark.png
